[build]
base = "."
command = "NODE_ENV=production CI=false npm install --include=dev && npm run build"
publish = "dist"

[build.environment]
VITE_SUPABASE_URL = "https://ilomxrbiyrybokbapasx.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsb214cmJpeXJ5Ym9rYmFwYXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDI0OTg0MTcsImV4cCI6MjAxODA3NDQxN30.GQDJZqCkqWyLYxz9ELG_JRgXgEGNyxQWgRJ_xHahxVo"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "https://deebeeai.com/*"
to = "https://www.deebeeai.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://deebeeai.com/*"
to = "https://www.deebeeai.com/:splat"
status = 301
force = true

[[redirects]]
from = "http://www.deebeeai.com/*"
to = "https://www.deebeeai.com/:splat"
status = 301
force = true

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self' https://ilomxrbiyrybokbapasx.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://deebeeai.com https://www.deebeeai.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://*.googleusercontent.com; connect-src 'self' https://ilomxrbiyrybokbapasx.supabase.co wss://ilomxrbiyrybokbapasx.supabase.co;"
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"